locale: "en-GB"
title: Liam Adamson
description: |
  Embedded software engineer based in London, UK.
email: liam@liamadamson.co.uk
github_username: liamadamson
domain: liamadamson.co.uk
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
url: https://www.liamadamson.co.uk
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-include-cache
defaults:
- scope:
    path: ""
    type: home
  values:
    author_profile: true
- scope:
    path: ""
    type: posts
  values:
    author_profile: true
    show_date: true
    read_time: true
- scope:
    path: ""
    type: single
  values:
    share: true
author:
  name: "Liam Adamson"
  bio: "Embedded software engineer specialising in embedded systems and IoT."
  avatar: "/assets/images/avatar.jpeg"
  location: "London, UK"
  links:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/liamadamson"
footer:
  links:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/liamadamson"
